/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ActiveMatchEntrant = Entrant & {
	score: number;
	[k: string]: unknown;
};

export interface ActiveMatch {
	entrantA: ActiveMatchEntrant;
	entrantB: ActiveMatchEntrant;
	match: {
		name: string;
		numberOfGames: number;
		playType: 'PLAY_ALL' | 'BEST_OF';
	};
	hideOnIntermission: boolean;
}
export interface Entrant {
	id: string;
	name: string;
	participants: Participant[];
	[k: string]: unknown;
}
export interface Participant {
	id: string;
	name: string;
	prefix?: string | null;
	[k: string]: unknown;
}
