/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RuntimeConfig {
	game:
		| 'TEKKEN'
		| 'TEKKEN_BALL'
		| 'MORTAL_KOMBAT'
		| 'SSBU'
		| 'SSBM'
		| 'STREET_FIGHTER_6'
		| 'MORTAL_KOMBAT_1'
		| '2XKO'
		| 'GGST'
		| 'MAIDEN_SPELL'
		| 'LETHAL_LEAGUE_BLAZE'
		| 'BLAZBLUE_CROSS_TAG_BATTLE'
		| 'MARVEL_TOKON';
}
