/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TournamentData {
	name: string;
	source: 'startgg' | 'unknown';
	sourceSpecificData?: {
		startgg?: {
			slug: string;
			eventId: number;
			streams: {
				id: number;
				streamName: string;
			}[];
		};
	};
}
